fruit = [
    'abiu',
    'açaí',
    'acerola',
    'ackee',
    'african cucumber',
    'apple',
    'apricot',
    'avocado',
    'banana',
    'bilberry',
    'blackberry',
    'blackcurrant',
    'black sapote',
    'blueberry',
    'boysenberry',
    'breadfruit',
    'buddha\'s hand',
    'cactus pear',
    'canistel',
    'cempedak',
    'crab apple',
    'cherimoya',
    'cherry',
    'chico fruit',
    'cloudberry',
    'coco de mer',
    'coconut',
    'cranberry',
    'currant',
    'damson',
    'date',
    'dragonfruit',
    'durian',
    'egg fruit',
    'elderberry',
    'feijoa',
    'fig',
    'goji berry',
    'gooseberry',
    'grape',
    'raisin',
    'grapefruit',
    'phalsa',
    'guava',
    'hala fruit',
    'honeyberry',
    'huckleberry',
    'jabuticaba',
    'jackfruit',
    'jambul',
    'japanese plum',
    'jostaberry',
    'jujube',
    'juniper berry',
    'kaffir lime',
    'kiwano',
    'kiwifruit',
    'kumquat',
    'lemon',
    'lime',
    'loganberry',
    'longan',
    'loquat',
    'lulo',
    'lychee',
    'magellan barberry',
    'mamey apple',
    'mamey sapote',
    'mango',
    'mangosteen',
    'marionberry',
    'melon',
    'cantaloupe',
    'galia melon',
    'honeydew',
    'mouse melon',
    'watermelon',
    'miracle fruit',
    'monstera deliciosa',
    'mulberry',
    'nance',
    'nectarine',
    'orange',
    'blood orange',
    'clementine',
    'mandarine',
    'tangerine',
    'papaya',
    'passionfruit',
    'peach',
    'pear',
    'persimmon',
    'plantain',
    'plum',
    'prune',
    'pineapple',
    'pineberry',
    'pluot',
    'pomegranate',
    'pomelo',
    'purple mangosteen',
    'quince',
    'raspberry',
    'salmonberry',
    'rambutan',
    'redcurrant',
    'rose apple',
    'salal berry',
    'salak',
    'satsuma',
    'vitis vinifera',
    'hawthorn berry',
    'soursop',
    'star apple',
    'star fruit',
    'strawberry',
    'surinam cherry',
    'tamarillo',
    'tamarind',
    'tangelo',
    'tayberry',
    'tomato',
    'ugli fruit',
    'white currant',
    'white sapote',
    'yuzu'
]
vegetable = [
    'artichoke',
    'aubergine',
    'asparagus',
    'alfalfa sprouts',
    'azuki beans',
    'bean sprouts',
    'black beans',
    'black-eyed peas',
    'borlotti bean',
    'broad beans',
    'chickpeas',
    'green beans',
    'kidney beans',
    'lentils',
    'lima beans',
    'mung beans',
    'navy beans',
    'peanuts',
    'pinto beans',
    'runner beans',
    'split peas',
    'soy beans',
    'peas',
    'snap peas',
    'broccoflower',
    'broccoli',
    'brussels sprouts',
    'cabbage',
    'kohlrabi',
    'Savoy cabbage',
    'red cabbage',
    'cauliflower',
    'celery',
    'endive',
    'fiddleheads',
    'frisee',
    'fennel',
    'greens',
    'bok choy',
    'chard',
    'collard greens',
    'kale',
    'mustard greens',
    'spinach',
    'herbs',
    'anise',
    'basil',
    'caraway',
    'coriander',
    'chamomile',
    'daikon',
    'dill',
    'fennel',
    'lavender',
    'lemongrass',
    'marjoram',
    'oregano',
    'parsley',
    'rosemary',
    'thyme',
    'lettuce',
    'arugula',
    'mushroom',
    'New Zealand spinach',
    'okra',
    'onions',
    'chives',
    'garlic',
    'leek',
    'onion',
    'shallot',
    'scallion',
    'bell pepper',
    'chili pepper',
    'jalapeño',
    'habanero',
    'paprika',
    'tabasco pepper',
    'cayenne pepper',
    'radicchio',
    'rhubarb',
    'beetroot (UK) beet (US)',
    'carrot',
    'celeriac',
    'corms',
    'eddoe',
    'konjac',
    'taro',
    'water chestnut',
    'ginger',
    'parsnip',
    'rutabaga',
    'radish',
    'wasabi',
    'horseradish',
    'Diakon or white radish',
    'tubers',
    'jicama',
    'jerusalem artichoke',
    'potato',
    'sweet potato',
    'yam',
    'turnip',
    'spinach',
    'salsify',
    'skirret',
    'sweetcorn',
    'topinambur',
    'acorn squash',
    'bitter melon',
    'butternut squash',
    'banana squash',
    'cucumber',
    'delicata',
    'gem squash',
    'hubbard squash',
    'spaghetti squash',
    'tat soi',
    'tomato',
    'watercress'
]
pastries = [
    'pie',
    'cake',
    'cheesecake',
    'charlotte',
    'danish'
]